use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Datei",
    edit: "Bearbeiten",
    format: "Format",
    view: "Ansicht",
    new_document: "Neu",
    open_document: "Öffnen...",
    save_document: "Speichern",
    save_document_as: "Speichern unter...",
    export: "Exportieren",
    export_pdf: "PDF exportieren",
    export_html: "HTML exportieren",
    settings: "Einstellungen...",
    undo: "Rückgängig",
    redo: "Wiederholen",
    cut: "Ausschneiden",
    copy: "Kopieren",
    paste: "Einfügen",
    select_all: "Alles auswählen",
    close_window: "Fenster schließen",
    hide: "Markra ausblenden",
    hide_others: "Andere ausblenden",
    show_all: "Alle einblenden",
    quit: "Markra beenden",
    fullscreen: "Vollbildmodus",
    bold: "Fett",
    italic: "Kursiv",
    strikethrough: "Durchgestrichen",
    inline_code: "Inline-Code",
    paragraph: "Absatz",
    heading_1: "Überschrift 1",
    heading_2: "Überschrift 2",
    heading_3: "Überschrift 3",
    bullet_list: "Aufzählung",
    ordered_list: "Nummerierte Liste",
    quote: "Zitat",
    code_block: "Codeblock",
    link: "Link",
    image: "Bild",
};
