use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "File",
    edit: "Edit",
    format: "Format",
    view: "View",
    new_document: "New",
    open_document: "Open...",
    open_folder: "Open Folder...",
    close_document: "Close File",
    save_document: "Save",
    save_document_as: "Save As...",
    export: "Export",
    export_pdf: "Export PDF",
    export_html: "Export HTML",
    settings: "Settings...",
    undo: "Undo",
    redo: "Redo",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    select_all: "Select All",
    hide: "Hide Markra",
    hide_others: "Hide Others",
    show_all: "Show All",
    quit: "Quit Markra",
    fullscreen: "Enter Full Screen",
    toggle_file_list: "Toggle File List",
    toggle_markra_ai: "Toggle Markra AI",
    ai_writing_command: "AI Writing Command",
    toggle_source_mode: "Toggle Source Mode",
    bold: "Bold",
    italic: "Italic",
    strikethrough: "Strikethrough",
    inline_code: "Inline Code",
    paragraph: "Paragraph",
    heading_1: "Heading 1",
    heading_2: "Heading 2",
    heading_3: "Heading 3",
    bullet_list: "Bullet List",
    ordered_list: "Ordered List",
    quote: "Quote",
    code_block: "Code Block",
    link: "Link",
    image: "Image",
    table: "Table",
};
