use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Archivo",
    edit: "Editar",
    format: "Formato",
    view: "Ver",
    new_document: "Nuevo",
    open_document: "Abrir...",
    open_folder: "Abrir carpeta...",
    save_document: "Guardar",
    save_document_as: "Guardar como...",
    export: "Exportar",
    export_pdf: "Exportar PDF",
    export_html: "Exportar HTML",
    settings: "Ajustes...",
    undo: "Deshacer",
    redo: "Rehacer",
    cut: "Cortar",
    copy: "Copiar",
    paste: "Pegar",
    select_all: "Seleccionar todo",
    close_window: "Cerrar ventana",
    hide: "Ocultar Markra",
    hide_others: "Ocultar otros",
    show_all: "Mostrar todo",
    quit: "Salir de Markra",
    fullscreen: "Pantalla completa",
    toggle_file_list: "Alternar lista de archivos",
    toggle_markra_ai: "Alternar Markra AI",
    ai_writing_command: "Comando de escritura con IA",
    toggle_source_mode: "Alternar modo fuente",
    bold: "Negrita",
    italic: "Cursiva",
    strikethrough: "Tachado",
    inline_code: "Código en línea",
    paragraph: "Párrafo",
    heading_1: "Encabezado 1",
    heading_2: "Encabezado 2",
    heading_3: "Encabezado 3",
    bullet_list: "Lista con viñetas",
    ordered_list: "Lista numerada",
    quote: "Cita",
    code_block: "Bloque de código",
    link: "Enlace",
    image: "Imagen",
    table: "Tabla",
};
