use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Fichier",
    edit: "Édition",
    format: "Format",
    view: "Affichage",
    new_document: "Nouveau",
    open_document: "Ouvrir...",
    open_folder: "Ouvrir un dossier...",
    save_document: "Enregistrer",
    save_document_as: "Enregistrer sous...",
    export: "Exporter",
    export_pdf: "Exporter en PDF",
    export_html: "Exporter en HTML",
    settings: "Réglages...",
    undo: "Annuler",
    redo: "Rétablir",
    cut: "Couper",
    copy: "Copier",
    paste: "Coller",
    select_all: "Tout sélectionner",
    close_window: "Fermer la fenêtre",
    hide: "Masquer Markra",
    hide_others: "Masquer les autres",
    show_all: "Tout afficher",
    quit: "Quitter Markra",
    fullscreen: "Plein écran",
    toggle_file_list: "Afficher ou masquer la liste des fichiers",
    toggle_markra_ai: "Afficher ou masquer Markra AI",
    ai_writing_command: "Commande d'écriture IA",
    toggle_source_mode: "Basculer le mode source",
    bold: "Gras",
    italic: "Italique",
    strikethrough: "Barré",
    inline_code: "Code en ligne",
    paragraph: "Paragraphe",
    heading_1: "Titre 1",
    heading_2: "Titre 2",
    heading_3: "Titre 3",
    bullet_list: "Liste à puces",
    ordered_list: "Liste numérotée",
    quote: "Citation",
    code_block: "Bloc de code",
    link: "Lien",
    image: "Image",
    table: "Tableau",
};
