use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Fichier",
    edit: "Édition",
    format: "Format",
    view: "Affichage",
    new_document: "Nouveau",
    open_document: "Ouvrir...",
    save_document: "Enregistrer",
    save_document_as: "Enregistrer sous...",
    settings: "Réglages...",
    undo: "Annuler",
    redo: "Rétablir",
    cut: "Couper",
    copy: "Copier",
    paste: "Coller",
    select_all: "Tout sélectionner",
    close_window: "Fermer la fenêtre",
    hide: "Masquer Markra",
    hide_others: "Masquer les autres",
    show_all: "Tout afficher",
    quit: "Quitter Markra",
    fullscreen: "Plein écran",
    bold: "Gras",
    italic: "Italique",
    strikethrough: "Barré",
    inline_code: "Code en ligne",
    paragraph: "Paragraphe",
    heading_1: "Titre 1",
    heading_2: "Titre 2",
    heading_3: "Titre 3",
    bullet_list: "Liste à puces",
    ordered_list: "Liste numérotée",
    quote: "Citation",
    code_block: "Bloc de code",
    link: "Lien",
    image: "Image",
};
