use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "File",
    edit: "Modifica",
    format: "Formato",
    view: "Vista",
    new_document: "Nuovo",
    open_document: "Apri...",
    open_folder: "Apri cartella...",
    close_document: "Chiudi file",
    save_document: "Salva",
    save_document_as: "Salva con nome...",
    export: "Esporta",
    export_pdf: "Esporta PDF",
    export_html: "Esporta HTML",
    settings: "Impostazioni...",
    undo: "Annulla",
    redo: "Ripeti",
    cut: "Taglia",
    copy: "Copia",
    paste: "Incolla",
    select_all: "Seleziona tutto",
    hide: "Nascondi Markra",
    hide_others: "Nascondi altri",
    show_all: "Mostra tutto",
    quit: "Esci da Markra",
    fullscreen: "Schermo intero",
    toggle_file_list: "Mostra/nascondi elenco file",
    toggle_markra_ai: "Mostra/nascondi Markra AI",
    ai_writing_command: "Comando di scrittura AI",
    toggle_source_mode: "Attiva/disattiva modalità sorgente",
    bold: "Grassetto",
    italic: "Corsivo",
    strikethrough: "Barrato",
    inline_code: "Codice inline",
    paragraph: "Paragrafo",
    heading_1: "Titolo 1",
    heading_2: "Titolo 2",
    heading_3: "Titolo 3",
    bullet_list: "Elenco puntato",
    ordered_list: "Elenco numerato",
    quote: "Citazione",
    code_block: "Blocco di codice",
    link: "Link",
    image: "Immagine",
    table: "Tabella",
};
