use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "ファイル",
    edit: "編集",
    format: "フォーマット",
    view: "表示",
    new_document: "新規",
    open_document: "開く...",
    save_document: "保存",
    save_document_as: "別名で保存...",
    export: "書き出し",
    export_pdf: "PDF に書き出す",
    export_html: "HTML に書き出す",
    settings: "設定...",
    undo: "取り消す",
    redo: "やり直す",
    cut: "カット",
    copy: "コピー",
    paste: "ペースト",
    select_all: "すべて選択",
    close_window: "ウインドウを閉じる",
    hide: "Markra を隠す",
    hide_others: "ほかを隠す",
    show_all: "すべてを表示",
    quit: "Markra を終了",
    fullscreen: "フルスクリーンにする",
    toggle_file_list: "ファイルリストを切り替え",
    toggle_markra_ai: "Markra AI を切り替え",
    ai_writing_command: "AI ライティングコマンド",
    toggle_source_mode: "ソースモードを切り替え",
    bold: "太字",
    italic: "斜体",
    strikethrough: "取り消し線",
    inline_code: "インラインコード",
    paragraph: "段落",
    heading_1: "見出し 1",
    heading_2: "見出し 2",
    heading_3: "見出し 3",
    bullet_list: "箇条書き",
    ordered_list: "番号付きリスト",
    quote: "引用",
    code_block: "コードブロック",
    link: "リンク",
    image: "画像",
    table: "表",
};
