use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "파일",
    edit: "편집",
    format: "서식",
    view: "보기",
    new_document: "새 문서",
    open_document: "열기...",
    open_folder: "폴더 열기...",
    close_document: "파일 닫기",
    save_document: "저장",
    save_document_as: "다른 이름으로 저장...",
    export: "내보내기",
    export_pdf: "PDF 내보내기",
    export_html: "HTML 내보내기",
    settings: "설정...",
    check_updates: "업데이트 확인",
    undo: "실행 취소",
    redo: "다시 실행",
    cut: "잘라내기",
    copy: "복사",
    paste: "붙여넣기",
    select_all: "모두 선택",
    hide: "Markra 가리기",
    hide_others: "기타 가리기",
    show_all: "모두 보기",
    quit: "Markra 종료",
    fullscreen: "전체 화면 시작",
    toggle_file_list: "파일 목록 전환",
    toggle_markra_ai: "Markra AI 전환",
    ai_writing_command: "AI 쓰기 명령",
    toggle_source_mode: "소스 모드 전환",
    bold: "굵게",
    italic: "기울임",
    strikethrough: "취소선",
    inline_code: "인라인 코드",
    paragraph: "단락",
    heading_1: "제목 1",
    heading_2: "제목 2",
    heading_3: "제목 3",
    bullet_list: "글머리 기호 목록",
    ordered_list: "번호 매기기 목록",
    quote: "인용",
    code_block: "코드 블록",
    link: "링크",
    image: "이미지",
    table: "표",
};
