use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Arquivo",
    edit: "Editar",
    format: "Formatar",
    view: "Exibir",
    new_document: "Novo",
    open_document: "Abrir...",
    close_document: "Fechar arquivo",
    save_document: "Salvar",
    save_document_as: "Salvar como...",
    export: "Exportar",
    export_pdf: "Exportar PDF",
    export_html: "Exportar HTML",
    settings: "Configurações...",
    undo: "Desfazer",
    redo: "Refazer",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    select_all: "Selecionar tudo",
    hide: "Ocultar Markra",
    hide_others: "Ocultar outros",
    show_all: "Mostrar tudo",
    quit: "Encerrar Markra",
    fullscreen: "Tela cheia",
    toggle_file_list: "Alternar lista de arquivos",
    toggle_markra_ai: "Alternar Markra AI",
    ai_writing_command: "Comando de escrita com IA",
    toggle_source_mode: "Alternar modo fonte",
    bold: "Negrito",
    italic: "Itálico",
    strikethrough: "Tachado",
    inline_code: "Código embutido",
    paragraph: "Parágrafo",
    heading_1: "Título 1",
    heading_2: "Título 2",
    heading_3: "Título 3",
    bullet_list: "Lista com marcadores",
    ordered_list: "Lista numerada",
    quote: "Citação",
    code_block: "Bloco de código",
    link: "Link",
    image: "Imagem",
    table: "Tabela",
};
