use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Файл",
    edit: "Правка",
    format: "Формат",
    view: "Вид",
    new_document: "Создать",
    open_document: "Открыть...",
    open_folder: "Открыть папку...",
    close_document: "Закрыть файл",
    save_document: "Сохранить",
    save_document_as: "Сохранить как...",
    export: "Экспорт",
    export_pdf: "Экспорт PDF",
    export_html: "Экспорт HTML",
    settings: "Настройки...",
    undo: "Отменить",
    redo: "Повторить",
    cut: "Вырезать",
    copy: "Копировать",
    paste: "Вставить",
    select_all: "Выбрать все",
    hide: "Скрыть Markra",
    hide_others: "Скрыть остальные",
    show_all: "Показать все",
    quit: "Завершить Markra",
    fullscreen: "Полноэкранный режим",
    toggle_file_list: "Показать или скрыть список файлов",
    toggle_markra_ai: "Показать или скрыть Markra AI",
    ai_writing_command: "Команда письма ИИ",
    toggle_source_mode: "Переключить режим исходника",
    bold: "Жирный",
    italic: "Курсив",
    strikethrough: "Зачёркнутый",
    inline_code: "Встроенный код",
    paragraph: "Абзац",
    heading_1: "Заголовок 1",
    heading_2: "Заголовок 2",
    heading_3: "Заголовок 3",
    bullet_list: "Маркированный список",
    ordered_list: "Нумерованный список",
    quote: "Цитата",
    code_block: "Блок кода",
    link: "Ссылка",
    image: "Изображение",
    table: "Таблица",
};
