use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "文件",
    edit: "编辑",
    format: "格式",
    view: "视图",
    new_document: "新建",
    open_document: "打开...",
    open_folder: "打开文件夹...",
    close_document: "关闭文件",
    save_document: "保存",
    save_document_as: "另存为...",
    export: "导出",
    export_pdf: "导出 PDF",
    export_html: "导出 HTML",
    settings: "设置...",
    check_updates: "检查更新",
    undo: "撤销",
    redo: "重做",
    cut: "剪切",
    copy: "复制",
    paste: "粘贴",
    select_all: "全选",
    hide: "隐藏 Markra",
    hide_others: "隐藏其他",
    show_all: "全部显示",
    quit: "退出 Markra",
    fullscreen: "进入全屏",
    toggle_file_list: "切换文件列表",
    toggle_markra_ai: "切换 Markra AI",
    ai_writing_command: "AI 写作命令",
    toggle_source_mode: "切换源码模式",
    bold: "加粗",
    italic: "斜体",
    strikethrough: "删除线",
    inline_code: "行内代码",
    paragraph: "段落",
    heading_1: "标题 1",
    heading_2: "标题 2",
    heading_3: "标题 3",
    bullet_list: "无序列表",
    ordered_list: "有序列表",
    quote: "引用",
    code_block: "代码块",
    link: "链接",
    image: "图片",
    table: "表格",
};
