use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "檔案",
    edit: "編輯",
    format: "格式",
    view: "檢視",
    new_document: "新增",
    open_document: "開啟...",
    save_document: "儲存",
    save_document_as: "另存新檔...",
    export: "匯出",
    export_pdf: "匯出 PDF",
    export_html: "匯出 HTML",
    settings: "設定...",
    undo: "復原",
    redo: "重做",
    cut: "剪下",
    copy: "複製",
    paste: "貼上",
    select_all: "全選",
    close_window: "關閉視窗",
    hide: "隱藏 Markra",
    hide_others: "隱藏其他",
    show_all: "全部顯示",
    quit: "結束 Markra",
    fullscreen: "進入全螢幕",
    bold: "粗體",
    italic: "斜體",
    strikethrough: "刪除線",
    inline_code: "行內程式碼",
    paragraph: "段落",
    heading_1: "標題 1",
    heading_2: "標題 2",
    heading_3: "標題 3",
    bullet_list: "項目符號清單",
    ordered_list: "編號清單",
    quote: "引用",
    code_block: "程式碼區塊",
    link: "連結",
    image: "圖片",
};
