use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    file: "Arquivo",
    edit: "Editar",
    format: "Formatar",
    view: "Exibir",
    new_document: "Novo",
    open_document: "Abrir...",
    save_document: "Salvar",
    save_document_as: "Salvar como...",
    settings: "Configurações...",
    undo: "Desfazer",
    redo: "Refazer",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    select_all: "Selecionar tudo",
    close_window: "Fechar janela",
    hide: "Ocultar Markra",
    hide_others: "Ocultar outros",
    show_all: "Mostrar tudo",
    quit: "Encerrar Markra",
    fullscreen: "Tela cheia",
    bold: "Negrito",
    italic: "Itálico",
    strikethrough: "Tachado",
    inline_code: "Código embutido",
    paragraph: "Parágrafo",
    heading_1: "Título 1",
    heading_2: "Título 2",
    heading_3: "Título 3",
    bullet_list: "Lista com marcadores",
    ordered_list: "Lista numerada",
    quote: "Citação",
    code_block: "Bloco de código",
    link: "Link",
    image: "Imagem",
};
